### ISSUE TITLE
Create automatic data retention reports for CDSA data

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/primed-django#162]
We need to store periodic reports of CDSA data access. Potential process:

- [x]  - ~~Write a Django management command to create tsv files with the information we need.~~ - already done
- [x]  - Ask BITE to mount /projects/primed on suwa
- [x]  - Create a `/projects/primed/records/cdsa` directory.
- [ ]  - Set up a cron job to run the `cdsa_records` management command weekly and output into a new directory (by date) in above directory, eg `--outdir /projects/primed/records/cdsa/2023-04-15`.
- [ ]  - Add `/projects/primed/records` to the lolo backup.

**Comment by amstilp** [comment]
Full command to run:
```
/var/www/django/primed_apps/primed-apps-activate.sh; python manage.py cdsa_records --outdir /projects/primed/records/cdsa/`date "+%Y-%m-%d"`
```

**Comment by amstilp** [comment]
@jonas now we have some actual CDSA data - would be good to get this running soon

**Comment by jmcarson** [comment]
Some notes on progress here:
outdir is just a positional for this command, not a named argument - I am fine with this, just an fyi if you wanted to change (this currently works:  python manage.py cdsa_records DIR) (this does not work: python manage.py cdsa_records --outdir DIR)
`manage.py cdsa_records: error: unrecognized arguments: --outdir`

primedweb user does not have permission to write to the directory /projects/primed/records/cdsa it requires group us_sph_biostat_computing_primed - do you want to add primedweb to that group or look into other options?

for reference on cron formatting restrictions, just as an fyi you need to escape '%' signs, so:
/var/www/django/primed_apps/primed-apps-activate.sh; python manage.py cdsa_records /projects/primed/records/cdsa/$(date +'\\%Y-\\%m-\\%d')

**Comment by amstilp** [comment]
Thanks! I emailed to ask about the permissions to see if BITE has any input.

For the outdir argument, I'll modify the management command since I like having the `--outdir` argument. Do you have a branch where you're working on this already? If so I'll commit to that branch, and if not I'll make one.

**Comment by jmcarson** [comment]
Sounds good. I do not have a branch, you can go ahead and create one

**Comment by amstilp** [comment]
Done, see branch here: https://github.com/UW-GAC/primed-django/tree/feature/cdsa-records-cron

**Comment by amstilp** [comment]
I made the branch into a pull request - you can add the cron files there
