### ISSUE TITLE
Add search to Study List

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/primed-django#621]
The StudyList view should contain search boxes for short name and full name. It can be similar to the search implemented in ACM using django-filter.

**Comment by amstilp** [comment]
@wkirdp this would be a good issue to work on - basically implementing a search similar to what you did in ACM.

**Comment by wkirdp** [comment]
Sounds good. I'm on it.

**Comment by amstilp** [comment]
Closed by #628
